package com.liqq.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_log
 */
public class SysLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.id
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.user_id
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   操作模块
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.module
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    private String module;

    /**
     * Database Column Remarks:
     *   操作状态 0成功 1 失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.status
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   方法
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.method
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    private String method;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.create_time
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   运行时间,单位毫秒
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.run_time
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    private Long runTime;

    /**
     * Database Column Remarks:
     *   参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.args
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    private String args;

    /**
     * Database Column Remarks:
     *   返回数据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.return_value
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    private String returnValue;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.remark
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.id
     *
     * @return the value of sys_log.id
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.id
     *
     * @param id the value for sys_log.id
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.user_id
     *
     * @return the value of sys_log.user_id
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.user_id
     *
     * @param userId the value for sys_log.user_id
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.module
     *
     * @return the value of sys_log.module
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.module
     *
     * @param module the value for sys_log.module
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.status
     *
     * @return the value of sys_log.status
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.status
     *
     * @param status the value for sys_log.status
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.method
     *
     * @return the value of sys_log.method
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.method
     *
     * @param method the value for sys_log.method
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.create_time
     *
     * @return the value of sys_log.create_time
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.create_time
     *
     * @param createTime the value for sys_log.create_time
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.run_time
     *
     * @return the value of sys_log.run_time
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public Long getRunTime() {
        return runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.run_time
     *
     * @param runTime the value for sys_log.run_time
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public void setRunTime(Long runTime) {
        this.runTime = runTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.args
     *
     * @return the value of sys_log.args
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public String getArgs() {
        return args;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.args
     *
     * @param args the value for sys_log.args
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public void setArgs(String args) {
        this.args = args == null ? null : args.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.return_value
     *
     * @return the value of sys_log.return_value
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public String getReturnValue() {
        return returnValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.return_value
     *
     * @param returnValue the value for sys_log.return_value
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public void setReturnValue(String returnValue) {
        this.returnValue = returnValue == null ? null : returnValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.remark
     *
     * @return the value of sys_log.remark
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.remark
     *
     * @param remark the value for sys_log.remark
     *
     * @mbg.generated Tue Aug 27 11:32:11 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}