package com.liqq.model;

import java.util.Date;

import org.springframework.security.core.GrantedAuthority;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_resource
 */
public class SysResource implements GrantedAuthority{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.id
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   父级id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.parent_id
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   资源代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.code
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    private String code;

    /**
     * Database Column Remarks:
     *   资源名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.name
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    private String name;

    /**
     * Database Column Remarks:
     *   资源路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.href
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    private String href;

    /**
     * Database Column Remarks:
     *   咨询排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.sort
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   资源类型 0菜单 1功能
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.type
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.create_time
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resource.update_time
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.id
     *
     * @return the value of sys_resource.id
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.id
     *
     * @param id the value for sys_resource.id
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.parent_id
     *
     * @return the value of sys_resource.parent_id
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.parent_id
     *
     * @param parentId the value for sys_resource.parent_id
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.code
     *
     * @return the value of sys_resource.code
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.code
     *
     * @param code the value for sys_resource.code
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.name
     *
     * @return the value of sys_resource.name
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.name
     *
     * @param name the value for sys_resource.name
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.href
     *
     * @return the value of sys_resource.href
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.href
     *
     * @param href the value for sys_resource.href
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.sort
     *
     * @return the value of sys_resource.sort
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.sort
     *
     * @param sort the value for sys_resource.sort
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.type
     *
     * @return the value of sys_resource.type
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.type
     *
     * @param type the value for sys_resource.type
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.create_time
     *
     * @return the value of sys_resource.create_time
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.create_time
     *
     * @param createTime the value for sys_resource.create_time
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resource.update_time
     *
     * @return the value of sys_resource.update_time
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resource.update_time
     *
     * @param updateTime the value for sys_resource.update_time
     *
     * @mbg.generated Wed Sep 11 09:32:31 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	@Override
	public String getAuthority() {
		return this.href;
	}
}