package com.liqq.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role_resource
 */
public class SysRoleResource {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   角色id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.role_id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Integer roleId;

    /**
     * Database Column Remarks:
     *   资源id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.resource_id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Integer resourceId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.create_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_resource.update_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.id
     *
     * @return the value of sys_role_resource.id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.id
     *
     * @param id the value for sys_role_resource.id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.role_id
     *
     * @return the value of sys_role_resource.role_id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.role_id
     *
     * @param roleId the value for sys_role_resource.role_id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.resource_id
     *
     * @return the value of sys_role_resource.resource_id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.resource_id
     *
     * @param resourceId the value for sys_role_resource.resource_id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.create_time
     *
     * @return the value of sys_role_resource.create_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.create_time
     *
     * @param createTime the value for sys_role_resource.create_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_resource.update_time
     *
     * @return the value of sys_role_resource.update_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_resource.update_time
     *
     * @param updateTime the value for sys_role_resource.update_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}