package com.liqq.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user
 */
public class SysUser {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   父id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.pid
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Integer pid;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.username
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private String password;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.mobile
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.realname
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private String realname;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.identity_number
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private String identityNumber;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private String email;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.birthday
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   性别 0 男 1 女
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sex
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Byte sex;

    /**
     * Database Column Remarks:
     *   地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.address
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private String address;

    /**
     * Database Column Remarks:
     *   头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.head_img_url
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private String headImgUrl;

    /**
     * Database Column Remarks:
     *   密码过期时间 null永不过期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password_expired_date
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Date passwordExpiredDate;

    /**
     * Database Column Remarks:
     *   帐号过期时间 null永不过期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.account_expired_date
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Date accountExpiredDate;

    /**
     * Database Column Remarks:
     *   是否可用 0可用 1禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.enabled
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Byte enabled;

    /**
     * Database Column Remarks:
     *   是否锁定 0 未锁定 1锁定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.account_locked
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Byte accountLocked;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.update_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.pid
     *
     * @return the value of sys_user.pid
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.pid
     *
     * @param pid the value for sys_user.pid
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.username
     *
     * @return the value of sys_user.username
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.username
     *
     * @param username the value for sys_user.username
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.mobile
     *
     * @return the value of sys_user.mobile
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.mobile
     *
     * @param mobile the value for sys_user.mobile
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.realname
     *
     * @return the value of sys_user.realname
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.realname
     *
     * @param realname the value for sys_user.realname
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.identity_number
     *
     * @return the value of sys_user.identity_number
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public String getIdentityNumber() {
        return identityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.identity_number
     *
     * @param identityNumber the value for sys_user.identity_number
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setIdentityNumber(String identityNumber) {
        this.identityNumber = identityNumber == null ? null : identityNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.birthday
     *
     * @return the value of sys_user.birthday
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.birthday
     *
     * @param birthday the value for sys_user.birthday
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sex
     *
     * @return the value of sys_user.sex
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sex
     *
     * @param sex the value for sys_user.sex
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.address
     *
     * @return the value of sys_user.address
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.address
     *
     * @param address the value for sys_user.address
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.head_img_url
     *
     * @return the value of sys_user.head_img_url
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.head_img_url
     *
     * @param headImgUrl the value for sys_user.head_img_url
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl == null ? null : headImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password_expired_date
     *
     * @return the value of sys_user.password_expired_date
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Date getPasswordExpiredDate() {
        return passwordExpiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password_expired_date
     *
     * @param passwordExpiredDate the value for sys_user.password_expired_date
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setPasswordExpiredDate(Date passwordExpiredDate) {
        this.passwordExpiredDate = passwordExpiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.account_expired_date
     *
     * @return the value of sys_user.account_expired_date
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Date getAccountExpiredDate() {
        return accountExpiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.account_expired_date
     *
     * @param accountExpiredDate the value for sys_user.account_expired_date
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setAccountExpiredDate(Date accountExpiredDate) {
        this.accountExpiredDate = accountExpiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.enabled
     *
     * @return the value of sys_user.enabled
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Byte getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.enabled
     *
     * @param enabled the value for sys_user.enabled
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.account_locked
     *
     * @return the value of sys_user.account_locked
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Byte getAccountLocked() {
        return accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.account_locked
     *
     * @param accountLocked the value for sys_user.account_locked
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setAccountLocked(Byte accountLocked) {
        this.accountLocked = accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.update_time
     *
     * @return the value of sys_user.update_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.update_time
     *
     * @param updateTime the value for sys_user.update_time
     *
     * @mbg.generated Tue Sep 10 19:31:15 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}