package com.liqq.dao.mysql;

import com.liqq.model.SysCache;
import com.liqq.model.SysCacheExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysCacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    long countByExample(SysCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    int deleteByExample(SysCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    int insert(SysCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    int insertSelective(SysCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    List<SysCache> selectByExampleWithBLOBs(SysCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    List<SysCache> selectByExample(SysCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    SysCache selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysCache record, @Param("example") SysCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") SysCache record, @Param("example") SysCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    int updateByExample(@Param("record") SysCache record, @Param("example") SysCacheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    int updateByPrimaryKeySelective(SysCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(SysCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cache
     *
     * @mbg.generated Mon Sep 09 14:29:17 CST 2019
     */
    int updateByPrimaryKey(SysCache record);
}